---
title: 'Examen 3. Predicción'
author: 'Carlos Iván Canto Varela, 315649888'
output: 
  pdf_document: 
    keep_tex: yes
---

\section{1. Predicción en el caso continuo}

```{r include = FALSE}

# Preparamiento del environment.

rm(list = ls(all.names = TRUE))
gc()

set.seed(666)

library(faraway)
library(ggplot2)
library(dplyr)
library(broom)
library(caret)
library(MASS)
library(glmnet)
library(mlbench)
library(tibble)
library(corrplot)
library(factoextra)


# Preprocesamiento de los datos.

data(fat)

  # Eliminación de variables a ignorar.

fat = subset(fat, select = -c(siri, density, free))

```

```{r echo = FALSE, fig.cap = 'Gráficas de dispersión para visualización de datos atípicos.', figures-side, fig.show = "hold", out.width = "60%"}

  # Identificación de outliers mediante gráficas de dispersión.

ggplot(data = fat, mapping = aes(x = weight, y = brozek)) + 
  geom_point(color = '#880808') + 
  labs(title = 'Peso vs. porcentaje de grasa corporal',
       x = 'Peso (libras)',
       y = 'Porcentaje (%)') +
  theme_bw()

ggplot(data = fat, mapping = aes(x = height, y = brozek)) + 
  geom_point(color = '#880808') +
  labs(title = 'Altura vs. porcentaje de grasa corporal',
       x = 'Altura (pulgadas)',
       y = 'Porcentaje (%)') +
  theme_bw()

```

\section{2. Clasificación supervisada}

\subsection{i) Análisis descriptivo}

```{r include = FALSE}

rm(list = ls(all.names = TRUE))
gc()

data(PimaIndiansDiabetes2)
Data = PimaIndiansDiabetes2

# Eliminación de variables con datos incompletos.

Data = na.omit(Data)

# Componentes principales.

aux_Data = Data %>% dplyr::select(-c('diabetes'))
aux_Data %>% cor(method = 'pearson') %>% round(digits = 3)

prin_comp = prcomp(scale(aux_Data, scale = TRUE), scale = FALSE)

```

```{r echo = FALSE, warning = FALSE, fig.cap = 'Visualizaciones de los predictores', fig.ncol = 2, out.width = '50%', fig.subcap = c('Número de embarazos', 'Concentración de glucosa', 'Presión diastólica', 'Grosor de la piel del tríceps', 'Suero de insulina a dos horas', 'Índice de masa corporal', 'Pedigree de diabetes', 'Edad'), fig.align = 'center'}

for (i in 1:(ncol(Data) - 1)){
  print(Data %>% ggplot(aes(x = diabetes, y = Data[, i], fill = diabetes, colour = diabetes)) +
          geom_boxplot() +
          scale_fill_manual(values = c('#880808','#280137')) +
          scale_colour_manual(values = c('pos' = 'white', 'neg' = 'black')) +
          geom_boxplot(color = 'black', fill = NA, fatten = 0) +
          labs(
            title = paste('Visualización para', colnames(Data)[i]),
            x = 'Diabetes',
            y = colnames(Data)[i])
  )
}

```

\subsection{ii) Componentes principales}

```{r echo = FALSE, warning = FALSE, fig.cap = 'Diagramas de dispersión entre los componentes principales', fig.ncol = 2, out.width = '50%', fig.subcap = c('Copmonentes uno y dos', 'Componentes uno y tres', 'Componentes dos y tres'), fig.align = 'center'}

fviz_pca_biplot(prin_comp, habillage = Data$diabetes, label = 'var',
                title = 'Diagrama de dispersión entre los CP 1 y 2'
                ) + theme_bw()

fviz_pca_biplot(prin_comp, axes = c(1,3), habillage = Data$diabetes,
                label = 'var',
                title = 'Diagrama de dispersión entre los CP 1 y 3'
                ) + theme_bw()

fviz_pca_biplot(prin_comp, axes = c(2,3), habillage = Data$diabetes,
                label = 'var',
                title = 'Diagrama de dispersión entre los CP 2 y 3'
                ) + theme_bw()


```
